# The URL the site will be built for
base_url = "https://k-ota.dev/"

title = "k-ota's weblog"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

theme = "zola-pickles"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [{name = "tags"}]

[slugify]
anchors = "off"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
katex_enable = true

analytics = "UA-172917470-1"
